dataset:
  pol_list: [
    "slot_mmi5x5_rHz_0_fields_epsilon_size_960x192_raw", "slot_mmi5x5_rHz_1_fields_epsilon_size_960x192_raw", 
    "slot_mmi5x5_rHz_2_fields_epsilon_size_960x192_raw", "slot_mmi5x5_rHz_3_fields_epsilon_size_960x192_raw",
    "slot_mmi5x5_rHz_4_fields_epsilon_size_960x192_raw", "slot_mmi5x5_rHz_5_fields_epsilon_size_960x192_raw",
    "slot_mmi5x5_rHz_6_fields_epsilon_size_960x192_raw", "slot_mmi5x5_rHz_7_fields_epsilon_size_960x192_raw",
    "slot_mmi5x5_rHz_8_fields_epsilon_size_960x192_raw", "slot_mmi5x5_rHz_9_fields_epsilon_size_960x192_raw",
  ]
  processed_dir: random_size10_slot_mmi5x5

criterion:
  name: cmse
  aux_output_weight: 0.0
  norm: True

aux_criterion:
  curl_loss:
    weight: 0.0
  tv_loss:
    weight: 0.0
  poynting_loss:
    weight: 0.0

optimizer:
  name: adam
  lr: 0.003
  weight_decay: 0.000

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0.00001

run:
  experiment: "mmi_ffno_train_slot_mmi5x5"
  n_epochs: 200
  batch_size: 4

quantize:
  weight_bit: 32
  input_bit: 32

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mmi/ffno/train_train_slot_mmi5x5"
  model_comment: "test"
  resume: 0
  restore_checkpoint: ""
  no_linear: 0


debug:
  verbose: 1

plot:
  train: True
  valid: True
  test: True
  interval: 1
  dir_name: train_r_pos_Hz5
