dataset:
  name: mmi
  root: "/home/local/eda-s01/hanqing/project/PACE/data"
  num_workers: 16
  img_height: 80
  img_width: 384
  train_valid_split_ratio: [0.7, 0.3]
  center_crop: null
  # unqiue params for resize raw data
  resize: False
  resize_mode: bilinear
  resize_style: 'trim'
  normalize: True
  data_ratio: 0.5
  n_test_samples: null
  n_valid_samples: null
  test_ratio: 0.2
  in_channels: 4
  transform: basic
  shuffle: 1
  pol_list: [
    "slot_mmi3x3_rHz_0_fields_epsilon_size_848x160_raw", "slot_mmi3x3_rHz_1_fields_epsilon_size_848x160_raw", 
    "slot_mmi3x3_rHz_2_fields_epsilon_size_848x160_raw", "slot_mmi3x3_rHz_3_fields_epsilon_size_848x160_raw",
    "slot_mmi3x3_rHz_4_fields_epsilon_size_848x160_raw", "slot_mmi3x3_rHz_5_fields_epsilon_size_848x160_raw",
    "slot_mmi3x3_rHz_6_fields_epsilon_size_848x160_raw", "slot_mmi3x3_rHz_7_fields_epsilon_size_848x160_raw",
    "slot_mmi3x3_rHz_8_fields_epsilon_size_848x160_raw", "slot_mmi3x3_rHz_9_fields_epsilon_size_848x160_raw",
  ]
  processed_dir: slots_mmi3x3
  # NOTE(hqzhu): check the mixup augmentation
  augment:
    mixup_alpha: 1.
    cutmix_alpha: 0.
    cutmix_minmax: null
    prob: 0.8
    switch_prob: 0.
    mode: elem
    correct_lam: True
    random_vflip_ratio: 0.5
  aux_augment:
    horizontal_flip: False
    horizontal_flip_prob: 0.5
  test_augment:
    mixup_alpha: 1.
    cutmix_alpha: 0.
    cutmix_minmax: null
    prob: 1
    switch_prob: 0.
    mode: elem
    correct_lam: True
    random_vflip_ratio: 0

criterion:
  name: cmse
  aux_output_weight: 0
  norm: False

aux_criterion:
  curl_loss:
    weight: 0.0
  tv_loss:
    weight: 0.0
    norm: False

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.000

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 8
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 10
  train_noise: 0
  sparse_data: 0
  sparse_data_prob: 0

quantize:
  weight_bit: 32
  input_bit: 32

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mmi/ffno/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "PACE2d"
  out_channels: 2
  domain_size: [8, 38.4] # um
  grid_step: 0.1 # um
  buffer_width: 0.0 # um
  wavelength: 1.55
  pos_encoding: exp
  pace_config:
    dim: 64
    kernel_list: [64, 64, 64, 64, 64, 64]
    kernel_size_list: [1, 1, 1, 1, 1, 1]
    hidden_list: [128]
    padding_list: [0, 0, 0, 0, 0, 0]
    mode_list: [[41, 193], [41, 193], [41, 193], [41, 193], [41, 193], [41, 193]]
    act_func: GELU
    act_thres: 100
    dropout_rate: 0.1
    norm_func: bn
    drop_path_rate: 0.0
    with_cp: False
    aug_path: False
    ffn: True
    ffn_dwconv: True
    conv_stem: True
    fno_bias: False
    block_skip: True
    layer_skip: True
    module_type: "pace_4x"
    pos: [5, 7, 9]
  aux_pace: False
  aux_pace_learn_residual: False
  aux_pace_aug_input: False
  aux_pace_aug_feature: False
  aux_pace_aug_feature_enhance: True
  aux_pace_config:
    dim: 64
    kernel_list: [64, 64, 64, 64, 64, 64]
    kernel_size_list: [1, 1, 1, 1, 1, 1]
    hidden_list: [128]
    padding_list: [0, 0, 0, 0, 0, 0]
    mode_list: [[41, 193], [41, 193], [41, 193], [41, 193], [41, 193], [41, 193]]
    act_func: GELU
    act_thres: 100
    dropout_rate: 0.1
    norm_func: bn
    drop_path_rate: 0.1
    with_cp: False
    aug_path: False
    ffn: True
    ffn_dwconv: True
    conv_stem: True
    fno_bias: False
    block_skip: True
    layer_skip: True
    module_type: "pace_4x"
    pos: [5, 7, 9]

debug:
  verbose: 1

plot:
  train: True
  valid: True
  test: True
  interval: 10
  root: plot
  dir_name: default

